name: Lint

on:
  pull_request:
    # Runs on PRs targeting main
    branches:
      - main

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    environment: Build
    env:
      NODE_ENV: development
      TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET}}
      BETTER_AUTH_URL: ${{secrets.BETTER_AUTH_URL}}
      AUTH_GITHUB_CLIENT_ID: ${{secrets.AUTH_GITHUB_CLIENT_ID}}
      AUTH_GITHUB_CLIENT_SECRET: ${{secrets.AUTH_GITHUB_CLIENT_SECRET}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Generate Nuxt types
        run: npm run postinstall
      - name: Run ESLint
        run: npm run lint
