name: Lint

on:
  push:
    # Runs on push to any branch
    branches:
      - "**"
  pull_request:
    # Runs on PRs targeting main
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
